In [1]:
import pandas as pd
import numpy as np

In [2]:
real = pd.read_csv('/Users/tamsopanat/Desktop/MedCMU - FamMed/Dustboy/result/pm25.csv', usecols=[0,3,4,5,6,7,8,9,10]).dropna()
real

,datetime,province,amphoe,tambon,local_name,pm25,pm10,temp,humid
18072,2026-01-01 00:00:00,ลำปาง,แม่เมาะ,จางเหนือ,ศพด.อบต.จางเหนือ (Outdoor) ต.จางเหนือ อ.แม่เมา...,33.00,37.22,23.23,57.53
18073,2026-01-01 01:00:00,ลำปาง,แม่เมาะ,จางเหนือ,ศพด.อบต.จางเหนือ (Outdoor) ต.จางเหนือ อ.แม่เมา...,32.33,36.89,22.70,57.93
18074,2026-01-01 02:00:00,ลำปาง,แม่เมาะ,จางเหนือ,ศพด.อบต.จางเหนือ (Outdoor) ต.จางเหนือ อ.แม่เมา...,29.56,32.44,22.18,58.46
18075,2026-01-01 03:00:00,ลำปาง,แม่เมาะ,จางเหนือ,ศพด.อบต.จางเหนือ (Outdoor) ต.จางเหนือ อ.แม่เมา...,28.44,30.22,21.70,58.95
18076,2026-01-01 04:00:00,ลำปาง,แม่เมาะ,จางเหนือ,ศพด.อบต.จางเหนือ (Outdoor) ต.จางเหนือ อ.แม่เมา...,27.78,29.22,21.25,59.60
...,...,...,...,...,...,...,...,...,...
2057519,2026-07-16 19:00:00,ลำปาง,แม่เมาะ,จางเหนือ,วัดปงแท่น หมู่บ้านปงแท่น ต.จางเหนือ อ.แม่เมาะ ...,7.11,12.56,24.53,91.93
2057520,2026-07-16 20:00:00,ลำปาง,แม่เมาะ,จางเหนือ,วัดปงแท่น หมู่บ้านปงแท่น ต.จางเหนือ อ.แม่เมาะ ...,9.89,15.89,24.22,92.90
2057521,2026-07-16 21:00:00,ลำปาง,แม่เมาะ,จางเหนือ,วัดปงแท่น หมู่บ้านปงแท่น ต.จางเหนือ อ.แม่เมาะ ...,12.78,17.00,24.21,93.93
2057522,2026-07-16 22:00:00,ลำปาง,แม่เมาะ,จางเหนือ,วัดปงแท่น หมู่บ้านปงแท่น ต.จางเหนือ อ.แม่เมาะ ...,12.11,17.33,24.33,93.87
2057523,2026-07-16 23:00:00,ลำปาง,แม่เมาะ,จางเหนือ,วัดปงแท่น หมู่บ้านปงแท่น ต.จางเหนือ อ.แม่เมาะ ...,12.00,17.00,24.37,93.60

In [3]:
real['local_name'] = real['local_name'].str.split(' ต.').str[0]
real

,datetime,province,amphoe,tambon,local_name,pm25,pm10,temp,humid
18072,2026-01-01 00:00:00,ลำปาง,แม่เมาะ,จางเหนือ,ศพด.อบต.จางเหนือ (Outdoor),33.00,37.22,23.23,57.53
18073,2026-01-01 01:00:00,ลำปาง,แม่เมาะ,จางเหนือ,ศพด.อบต.จางเหนือ (Outdoor),32.33,36.89,22.70,57.93
18074,2026-01-01 02:00:00,ลำปาง,แม่เมาะ,จางเหนือ,ศพด.อบต.จางเหนือ (Outdoor),29.56,32.44,22.18,58.46
18075,2026-01-01 03:00:00,ลำปาง,แม่เมาะ,จางเหนือ,ศพด.อบต.จางเหนือ (Outdoor),28.44,30.22,21.70,58.95
18076,2026-01-01 04:00:00,ลำปาง,แม่เมาะ,จางเหนือ,ศพด.อบต.จางเหนือ (Outdoor),27.78,29.22,21.25,59.60
...,...,...,...,...,...,...,...,...,...
2057519,2026-07-16 19:00:00,ลำปาง,แม่เมาะ,จางเหนือ,วัดปงแท่น หมู่บ้านปงแท่น,7.11,12.56,24.53,91.93
2057520,2026-07-16 20:00:00,ลำปาง,แม่เมาะ,จางเหนือ,วัดปงแท่น หมู่บ้านปงแท่น,9.89,15.89,24.22,92.90
2057521,2026-07-16 21:00:00,ลำปาง,แม่เมาะ,จางเหนือ,วัดปงแท่น หมู่บ้านปงแท่น,12.78,17.00,24.21,93.93
2057522,2026-07-16 22:00:00,ลำปาง,แม่เมาะ,จางเหนือ,วัดปงแท่น หมู่บ้านปงแท่น,12.11,17.33,24.33,93.87
2057523,2026-07-16 23:00:00,ลำปาง,แม่เมาะ,จางเหนือ,วัดปงแท่น หมู่บ้านปงแท่น,12.00,17.00,24.37,93.60

In [4]:
real = real[real['province'].isin(['เชียงราย', 'เชียงใหม่', 'แม่ฮ่องสอน', 'ลำปาง', 'ลำพูน', 'น่าน', 'แพร่', 'พะเยา'])]
real = real[real['datetime'] >= '2026-04-01 00:00:00']
real = real[['datetime', 'province', 'amphoe', 'tambon', 'local_name', 'pm25', 'temp']]
real.columns = ['date','province','amphoe','tambon','local_name','pm25_avg','temperature_avg']
real.to_csv('./environmental.csv', index= False)
real

,date,province,amphoe,tambon,local_name,pm25_avg,temperature_avg
966619,2026-04-01 00:00:00,ลำปาง,แม่เมาะ,จางเหนือ,ศพด.อบต.จางเหนือ (Outdoor),138.67,31.82
966620,2026-04-01 01:00:00,ลำปาง,แม่เมาะ,จางเหนือ,ศพด.อบต.จางเหนือ (Outdoor),149.78,31.17
966621,2026-04-01 02:00:00,ลำปาง,แม่เมาะ,จางเหนือ,ศพด.อบต.จางเหนือ (Outdoor),170.00,30.53
966622,2026-04-01 03:00:00,ลำปาง,แม่เมาะ,จางเหนือ,ศพด.อบต.จางเหนือ (Outdoor),202.50,30.14
966623,2026-04-01 04:00:00,ลำปาง,แม่เมาะ,จางเหนือ,ศพด.อบต.จางเหนือ (Outdoor),301.91,29.37
...,...,...,...,...,...,...,...
2057519,2026-07-16 19:00:00,ลำปาง,แม่เมาะ,จางเหนือ,วัดปงแท่น หมู่บ้านปงแท่น,7.11,24.53
2057520,2026-07-16 20:00:00,ลำปาง,แม่เมาะ,จางเหนือ,วัดปงแท่น หมู่บ้านปงแท่น,9.89,24.22
2057521,2026-07-16 21:00:00,ลำปาง,แม่เมาะ,จางเหนือ,วัดปงแท่น หมู่บ้านปงแท่น,12.78,24.21
2057522,2026-07-16 22:00:00,ลำปาง,แม่เมาะ,จางเหนือ,วัดปงแท่น หมู่บ้านปงแท่น,12.11,24.33
2057523,2026-07-16 23:00:00,ลำปาง,แม่เมาะ,จางเหนือ,วัดปงแท่น หมู่บ้านปงแท่น,12.00,24.37

In [16]:
import csv
import random
import math
from datetime import datetime, timedelta

locations = {}
for province, amphoe, tambon in real[['province', 'amphoe', 'tambon']].drop_duplicates().itertuples(index=False):
    locations.setdefault(province, {}).setdefault(amphoe, []).append(tambon)

start_date = datetime(2026, 4, 1, 0, 0, 0)
end_date = datetime(2026, 6, 30, 23, 0, 0)
num_days = (end_date - start_date).days
num_hours = num_days * 24


pat_filename = "patients.csv"
pat_headers = [
    "patient_id", "name_masked", "sex", "age", "province", "amphoe", "tambon", "last_contact_date",
    "child_5", "newborn", "outdoor_athlete", "obesity", "underweight", 
    "bpd", "recurrent_rti", "asthma", "allergic_rhinitis", "chd", "fever", "kidney_disease", "neurologic_disease",
    "beta_blocker", "antihistamine", "diuretic"
]

thai_first_names = ["Somchai", "Mali", "Anong", "Kittipong", "Siriporn", "Nattapong", "Wipawan", "Surasak", "Pornthip", "Arunee"]
thai_last_initials = ["P.", "S.", "W.", "K.", "T.", "N.", "J.", "M."]

    
with open(pat_filename, mode="w", newline="", encoding="utf-8") as f:
    writer = csv.writer(f)
    writer.writerow(pat_headers)
    
    # Generate 1500 mock patients
    for i in range(1, 1501):
        pid = f"CM-{random.randint(1000, 9999)}"
        name = f"{random.choice(thai_first_names)} {random.choice(thai_last_initials)}"
        sex = random.choice(["M", "F"])
        age = random.randint(0, 90)
        
        prov = random.choice(list(locations.keys()))
        amphoe = random.choice(list(locations[prov].keys()))
        tambon = random.choice(locations[prov][amphoe])
        
        contact_days_ago = random.randint(1, 60)
        contact_date = (start_date + timedelta(days=num_days) - timedelta(days=contact_days_ago)).strftime("%Y-%m-%d")
        
        # Demographics booleans based on age constraints
        child_5 = age <= 5
        newborn = age <= 1
        outdoor_athlete = 12 <= age <= 40 and random.random() < 0.15
        obesity = random.random() < 0.1
        underweight = random.random() < 0.05
        
        # Health conditions booleans
        age_factor = age / 100
        bpd = newborn and random.random() < 0.05
        recurrent_rti = child_5 and random.random() < 0.2
        asthma = random.random() < 0.15
        allergic_rhinitis = random.random() < 0.2
        chd = random.random() < 0.02
        fever = random.random() < 0.05
        kidney_disease = random.random() < (0.02 + age_factor * 0.2)
        neurologic_disease = random.random() < (0.01 + age_factor * 0.1)
        
        beta_blocker = random.random() < (0.05 + age_factor * 0.4)
        antihistamine = random.random() < 0.15
        diuretic = random.random() < (0.02 + age_factor * 0.3)
        
        writer.writerow([
            pid, name, sex, age, prov, amphoe, tambon, contact_date,
            child_5, newborn, outdoor_athlete, obesity, underweight,
            bpd, recurrent_rti, asthma, allergic_rhinitis, chd, fever, kidney_disease, neurologic_disease,
            beta_blocker, antihistamine, diuretic
        ])

print(f"✅ Generated {pat_filename} successfully.")

✅ Generated patients.csv successfully.

In [13]:
real = pd.read_csv('./environmental.csv')
real

,date,province,amphoe,tambon,local_name,pm25_avg,temperature_avg
0,2026-04-01 00:00:00,ลำปาง,แม่เมาะ,จางเหนือ,ศพด.อบต.จางเหนือ (Outdoor),138.67,31.82
1,2026-04-01 01:00:00,ลำปาง,แม่เมาะ,จางเหนือ,ศพด.อบต.จางเหนือ (Outdoor),149.78,31.17
2,2026-04-01 02:00:00,ลำปาง,แม่เมาะ,จางเหนือ,ศพด.อบต.จางเหนือ (Outdoor),170.00,30.53
3,2026-04-01 03:00:00,ลำปาง,แม่เมาะ,จางเหนือ,ศพด.อบต.จางเหนือ (Outdoor),202.50,30.14
4,2026-04-01 04:00:00,ลำปาง,แม่เมาะ,จางเหนือ,ศพด.อบต.จางเหนือ (Outdoor),301.91,29.37
...,...,...,...,...,...,...,...
286703,2026-07-16 19:00:00,ลำปาง,แม่เมาะ,จางเหนือ,วัดปงแท่น หมู่บ้านปงแท่น,7.11,24.53
286704,2026-07-16 20:00:00,ลำปาง,แม่เมาะ,จางเหนือ,วัดปงแท่น หมู่บ้านปงแท่น,9.89,24.22
286705,2026-07-16 21:00:00,ลำปาง,แม่เมาะ,จางเหนือ,วัดปงแท่น หมู่บ้านปงแท่น,12.78,24.21
286706,2026-07-16 22:00:00,ลำปาง,แม่เมาะ,จางเหนือ,วัดปงแท่น หมู่บ้านปงแท่น,12.11,24.33
286707,2026-07-16 23:00:00,ลำปาง,แม่เมาะ,จางเหนือ,วัดปงแท่น หมู่บ้านปงแท่น,12.00,24.37

In [7]:
real['amphoe'].unique()

array(['แม่เมาะ', 'เมืองลำปาง', 'หางดง', 'ดอยเต่า', 'ดอยสะเก็ด',
       'สันกำแพง', 'เมืองเชียงใหม่', 'สันป่าตอง', 'อมก๋อย', 'เชียงคำ',
       'มือง', 'ดอกคำใต้', 'ภูซาง', 'จุน', 'เชียงม่วน', 'เมือง', 'ลี้',
       'แม่ทา', 'เมืองลำพูน', 'ทุ่งหัวช้าง', 'บ้านโฮ่ง', 'เชียงของ',
       'พาน', 'แม่สาย', 'แม่ลาน้อย', 'ขุนยวม', 'แม่วาง', 'ทุ่งช้าง',
       'สบเมย', 'นาน้อย', 'เชียงดาว', 'แม่แตง', 'เวียงเชียงรุ้ง', 'ปาย',
       'เฉลิมพระเกียรติ', 'ห้างฉัตร', 'ภูเพียง', 'แม่ฟ้าหลวง', 'แม่สรวย',
       'เวียงป่าเป้า', 'ภูกามยาว', 'แม่อาย', 'สูงเม่น', 'เวียงชัย',
       'จอมทอง', 'วังชิ้น', 'ฮอด', 'ดอยหล่อ', 'สารภี', 'แม่แจ่ม',
       'แม่สะเรียง', 'พร้าว', 'เวียงแก่น', 'หนองม่วงไข่', 'สันทราย',
       'ปางมะผ้า', 'แม่ริม', 'บ่อเกลือ'], dtype=object)

In [14]:
real.loc[real['amphoe'].str.contains('มือง', na=False), 'amphoe'] = 'เมือง'
real['amphoe'].unique()

array(['แม่เมาะ', 'เมือง', 'หางดง', 'ดอยเต่า', 'ดอยสะเก็ด', 'สันกำแพง',
       'สันป่าตอง', 'อมก๋อย', 'เชียงคำ', 'ดอกคำใต้', 'ภูซาง', 'จุน',
       'เชียงม่วน', 'ลี้', 'แม่ทา', 'ทุ่งหัวช้าง', 'บ้านโฮ่ง', 'เชียงของ',
       'พาน', 'แม่สาย', 'แม่ลาน้อย', 'ขุนยวม', 'แม่วาง', 'ทุ่งช้าง',
       'สบเมย', 'นาน้อย', 'เชียงดาว', 'แม่แตง', 'เวียงเชียงรุ้ง', 'ปาย',
       'เฉลิมพระเกียรติ', 'ห้างฉัตร', 'ภูเพียง', 'แม่ฟ้าหลวง', 'แม่สรวย',
       'เวียงป่าเป้า', 'ภูกามยาว', 'แม่อาย', 'สูงเม่น', 'เวียงชัย',
       'จอมทอง', 'วังชิ้น', 'ฮอด', 'ดอยหล่อ', 'สารภี', 'แม่แจ่ม',
       'แม่สะเรียง', 'พร้าว', 'เวียงแก่น', 'หนองม่วงไข่', 'สันทราย',
       'ปางมะผ้า', 'แม่ริม', 'บ่อเกลือ'], dtype=object)

In [15]:
real.to_csv('./environmental.csv', index=False)

In [10]:
asd

NameError: name 'asd' is not defined

In [ ]:
real = pd.read_csv('/Users/tamsopanat/Desktop/MedCMU - FamMed/Dustboy/result/pm25.csv')
real

,datetime,date,hour,province,amphoe,tambon,local_name,pm25,pm10,temp,humid
0,2026-01-01 00:00:00,2026-01-01,0,เชียงใหม่,เมือง,ช้างม่อย,ไนท์บาร์ซาร์ ต.ช้างม่อย อ.เมือง จ. เชียงใหม่,97.13,103.53,NaN,NaN
1,2026-01-01 01:00:00,2026-01-01,1,เชียงใหม่,เมือง,ช้างม่อย,ไนท์บาร์ซาร์ ต.ช้างม่อย อ.เมือง จ. เชียงใหม่,97.04,103.53,NaN,NaN
2,2026-01-01 02:00:00,2026-01-01,2,เชียงใหม่,เมือง,ช้างม่อย,ไนท์บาร์ซาร์ ต.ช้างม่อย อ.เมือง จ. เชียงใหม่,63.83,73.45,NaN,NaN
3,2026-01-01 03:00:00,2026-01-01,3,เชียงใหม่,เมือง,ช้างม่อย,ไนท์บาร์ซาร์ ต.ช้างม่อย อ.เมือง จ. เชียงใหม่,54.81,66.93,NaN,NaN
4,2026-01-01 04:00:00,2026-01-01,4,เชียงใหม่,เมือง,ช้างม่อย,ไนท์บาร์ซาร์ ต.ช้างม่อย อ.เมือง จ. เชียงใหม่,49.17,60.68,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...
2057519,2026-07-16 19:00:00,2026-07-16,19,ลำปาง,แม่เมาะ,จางเหนือ,วัดปงแท่น หมู่บ้านปงแท่น ต.จางเหนือ อ.แม่เมาะ ...,7.11,12.56,24.53,91.93
2057520,2026-07-16 20:00:00,2026-07-16,20,ลำปาง,แม่เมาะ,จางเหนือ,วัดปงแท่น หมู่บ้านปงแท่น ต.จางเหนือ อ.แม่เมาะ ...,9.89,15.89,24.22,92.90
2057521,2026-07-16 21:00:00,2026-07-16,21,ลำปาง,แม่เมาะ,จางเหนือ,วัดปงแท่น หมู่บ้านปงแท่น ต.จางเหนือ อ.แม่เมาะ ...,12.78,17.00,24.21,93.93
2057522,2026-07-16 22:00:00,2026-07-16,22,ลำปาง,แม่เมาะ,จางเหนือ,วัดปงแท่น หมู่บ้านปงแท่น ต.จางเหนือ อ.แม่เมาะ ...,12.11,17.33,24.33,93.87
2057523,2026-07-16 23:00:00,2026-07-16,23,ลำปาง,แม่เมาะ,จางเหนือ,วัดปงแท่น หมู่บ้านปงแท่น ต.จางเหนือ อ.แม่เมาะ ...,12.00,17.00,24.37,93.60

In [ ]:
# Group the entire DataFrame by province and get all unique local names
real = real[real['province'].isin(['เชียงราย', 'เชียงใหม่', 'แม่ฮ่องสอน', 'ลำปาง', 'ลำพูน', 'น่าน', 'แพร่', 'พะเยา'])]
all_stations_by_province = real.groupby('province')['local_name'].unique().to_dict()

# Loop through and print the stations for each province
for province, stations in all_stations_by_province.items():
    # Adding the count so you know how many stations are in each province
    print(f"📍 {province} ({len(stations)} stations)")
    
    for station in sorted(stations):
        print(f"   - {station}")
        
    print("-" * 30) # Separator for readability

📍 น่าน (15 stations)
   - บ้านปอน ต.ปอน อ.ทุ่งช้าง จ.น่าน
   - รพ.นาหมื่น ต.บ่อแก้ว อ.นาหมื่น จ.น่าน
   - รพ.บ่อเกลือ ต.บ่อเกลือใต้ อ.บ่อเกลือ จ.น่าน
   - รพ.บ้านหลวง ต.สวด อ.บ้านหลวง จ.น่าน
   - ศพด.ตำบลนาปัง (Indoor) อบต.นาปัง อ.ภูเพียง จ.น่าน
   - ศพด.ตำบลนาปัง (Outdoor) อบต.นาปัง อ.ภูเพียง จ.น่าน
   - ศพด.ตำบลบ่อเกลือใต้ (indoor) ต.บ่อเกลือใต้ อ.บ่อเกลือ จ.น่าน
   - ศพด.ตำบลบ่อเกลือใต้ (outdoor) ต.บ่อเกลือใต้ อ.บ่อเกลือ จ.น่าน
   - ศพด.บ้านห้วยโก๋น (Indoor) ต.ห้วยโก๋น อ.เฉลิมพระเกียรติ จ.น่าน
   - ศพด.บ้านห้วยโก๋น (Outdoor) ต.ห้วยโก๋น อ.เฉลิมพระเกียรติ จ.น่าน
   - สสช.บ้านสบปืน ต.ห้วยโก๋น อ.เฉลิมพระเกียรติ จ.น่าน
   - อบต.สวด ต.สวด อ.บ้านหลวง จ.น่าน
   - โรงพยาบาลนาน้อย ต.ศรีษะเกษ อ.นาน้อย จ.น่าน
   - โรงเรียนชุมชนบ้านเฟือยลุง ต.และ อ.ทุ่งช้าง จ.น่าน
   - โรงเรียนบ้านสบปืน ต.ห้วยโก๋น อ.เฉลิมพระเกียรติ จ.น่าน
------------------------------
📍 พะเยา (26 stations)
   - รพ.จุน ต.ห้วยข้าวก่ำ อ.จุน จ.พะเยา
   - รพ.ปง ต.นาปรัง อ.ปง จ.พะเยา
   - รพ.สต. บ้านต๊ำ  อ.เมือง จ.พะเยา
   - รพ.สต.ดงสุวรรณ อ.ดอกคำใต้ จ.พะเยา
   - รพ.สต.ดอกคำใต้ ต.ดอกคำใต้ อ.ดอกคำใต้ จ.พะเยา
   - รพ.สต.ทุ่งกล้วย  อ.ภูซาง จ.พะเยา
   - รพ.สต.ท่าวังทอง  อ.มือง จ.พะเยา
   - รพ.สต.บ้านบ่อเบี้ย อ.เชียงม่วน จ.พะเยา
   - รพ.สต.บ้านฝายกวาง  อ.เชียงคำ จ.พะเยา
   - รพ.สต.บ้านสักลอ อ.จุน จ.พะเยา
   - รพ.สต.บ้านหนองป่าแพะ ต.ร่มเย็น อ.เชียงคำ จ.พะเยา
   - รพ.สต.บ้านฮวก ต.ภูซาง อ.ภูซาง จ.พะเยา
   - รพ.สต.ลอ อ.จุน จ.พะเยา
   - รพ.สต.เวียง อ.เชียงคำ จ.พะเยา
   - รพ.สต.แม่ลาว อ.เชียงคำ จ.พะเยา
   - รพ.เชียงม่วน ต.เชียงม่วน อ.เชียงม่วน จ. พะเยา
   - รร.อนุบาลจุน(บ้านบัวสถาน) ต.ห้วยข้าวก่ำ อ.จุน จ.พะเยา
   - ศพด.จุน (Indoor) ต.จุน อ.จุน จ.พะเยา
   - ศพด.จุน (Outdoor) ต.จุน อ.จุน จ.พะเยา
   - ศพด.ทต.ห้วยลาน (Outdoor) ต.ห้วยลาน อ.ดอกคำใต้ จ.พะเยา
   - ศพด.ทต.ห้วยลาน (indoor) ต.ห้วยลาน อ.ดอกคำใต้ จ.พะเยา
   - ศพด.แม่ลาว (Outdoor) ต.แม่ลาว อ.เชียงคำ จ.พะเยา
   - ศพด.แม่ลาว (indoor) ต.แม่ลาว อ.เชียงคำ จ.พะเยา
   - สสอ.ดอกคำใต้ ต.ดอนศรีชุม อ.ดอกคำใต้ จ.พะเยา
   - โรงพยาบาลภูกามยาว  ต.ห้วยแก้ว อ.ภูกามยาว จ.พะเยา
   - โรงพยาบาลภูกามยาว2  ต.ห้วยแก้ว อ.ภูกามยาว จ.พะเยา
------------------------------
📍 ลำปาง (37 stations)
   - ชุมชนอิ่วเมี่ยน หมู่บ้านบ้านผาลาด ต.พระบาท อ.เมือง จ.ลำปาง
   - ทต.วังเหนือ ต.วังเหนือ อ.วังเหนือ จ.ลำปาง
   - ทต.ไหล่หิน ต.ไหล่หิน อ.เกาะคา จ.ลำปาง
   - นิคมชุมชนเกษตร ต.บ้านดง อ.แม่เมาะ จ.ลำปาง
   - บ้านหาดสามัคคี ต.จางเหนือ อ.แม่เมาะ จ.ลำปาง
   - รร.อนุบาลแม่เมาะ (Outdoor) ต.แม่เมาะ อ.แม่เมาะ จ.ลำปาง
   - รร.อนุบาลแม่เมาะ (indoor) ต.แม่เมาะ อ.แม่เมาะ จ.ลำปาง
   - รร.แม่เมาะวิทยา (indoor) ต.แม่เมาะ อ.แม่เมาะ จ.ลำปาง
   - วัดกอรวก หมู่บ้านกอรวก ต.จางเหนือ อ.แม่เมาะ จ.ลำปาง
   - วัดนาแช่ หมู่บ้านนาแช่ ต.จางเหนือ อ.แม่เมาะ จ.ลำปาง
   - วัดปงแท่น หมู่บ้านปงแท่น ต.จางเหนือ อ.แม่เมาะ จ.ลำปาง
   - วัดวังตม หมู่บ้านวังตม ต.จางเหนือ อ.แม่เมาะ จ.ลำปาง
   - ศพด.บ้านปันง้าว (Indoor) ต.ห้างฉัตร อ.ห้างฉัตร จ.ลำปาง
   - ศพด.บ้านปันง้าว (Outdoor) ต.ห้างฉัตร อ.ห้างฉัตร จ.ลำปาง
   - ศพด.บ้านศรีลังกา(บ้านหัวแต) (Indoor) ต.เสริมกลาง อ.เสริมงาม จ.ลำปาง
   - ศพด.บ้านศรีลังกา(บ้านหัวแต) (Outdoor) ต.เสริมกลาง อ.เสริมงาม จ.ลำปาง
   - ศพด.อบต.จางเหนือ (Indoor) ต.จางเหนือ อ.แม่เมาะ จ.ลำปาง
   - ศพด.อบต.จางเหนือ (Outdoor) ต.จางเหนือ อ.แม่เมาะ จ.ลำปาง
   - ศพด.เทศบาลเวียงตาล (Indoor) ต.เวียงตาล อ.ห้างฉัตร จ.ลำปาง
   - ศพด.เทศบาลเวียงตาล (Outdoor) ต.เวียงตาล อ.ห้างฉัตร จ.ลำปาง
   - ศูนย์บริการสาธารณสุขบ้านกล้วยแพะ ต.กล้วยแพะ อ.เมือง จ.ลำปาง
   - ศูนย์บริการสาธารณสุขบ้านกาด ต.ปงแสน อ.เมือง จ.ลำปาง
   - ศูนย์บริการสาธารณสุขบ้านฟ่อน   ต.ชมพู อ.มือง จ.ลำปาง
   - ศูนย์บริการสาธารณสุขบ้านแม่กืย ต.ปงแสนทอง อ.เมือง จ.ลำปาง
   - ศูนย์บริการสาธารณสุขบ้านโทกหัวช้าง ต.พระบาท อ.เมือง จ.ลำปาง
   - ศูนย์พัฒนาการจัดสวัสดิการสังคมผู้สูงอายุจังหวัดลำปาง ต.นิคมพัฒนา อ.เมืองลำปาง จ.ลำปาง
   - ศูนย์พัฒนาการจัดสวัสดิการสังคมผู้สูงอายุจังหวัดลำปาง ตึกผู้ป่วย ชาย (indoor) ต.นิคมพัฒนา อ.เมืองลำปาง จ.ลำปาง
   - ศูนย์พัฒนาการจัดสวัสดิการสังคมผู้สูงอายุจังหวัดลำปาง ตึกผู้ป่วย หญิง (indoor) ต.นิคมพัฒนา อ.เมืองลำปาง จ.ลำปาง
   - ศูนย์พัฒนาการจัดสวัสดิการสังคมผู้สูงอายุจังหวัดลำปาง ตึกแข็งแรง ชาย (indoor) ต.นิคมพัฒนา อ.เมืองลำปาง จ.ลำปาง
   - ศูนย์พัฒนาการจัดสวัสดิการสังคมผู้สูงอายุจังหวัดลำปาง ตึกแข็งแรง หญิง (indoor) ต.นิคมพัฒนา อ.เมืองลำปาง จ.ลำปาง
   - ศูนย์พัฒนาเด็กเล็ก (Outdoor) อบต.นาสัก ต.นาสัก อ.แม่เมาะ จ.ลำปาง
   - ศูนย์พัฒนาเด็กเล็ก (indoor) อบต.นาสัก ต.นาสัก อ.แม่เมาะ จ.ลำปาง
   - ศูนย์พัฒนาเด็กเล็ก อบต.สบป้าด ต.สบป้าด อ.แม่เมาะ จ.ลำปาง
   - อาคารอเนกประสงค์บ้านทาน หมู่บ้านบ้านทาน ต.จางเหนือ อ.แม่เมาะ จ.ลำปาง
   - โรงเรียนนาสัก หมู่บ้านนาสัก ต.นาสัก อ.แม่เมาะ จ.ลำปาง
   - โรงเรียนบ้านแม่ส้าน หมู่บ้านบ้านแม่ส้าน ต.บ้านดง อ.แม่เมาะ จ.ลำปาง
   - โรงเรียนแม่เมาะวิทยา ต.แม่เมาะ อ.แม่เมาะ จ.ลำปาง
------------------------------
📍 ลำพูน (31 stations)
   - จุดเฝ้าระวังฝุ่น PM ต.เหมืองจี้ อ.เมือง บ้านฝั่งหมิ่น จ.ลำพูน
   - จุดเฝ้าระวังฝุ่น PM ทต.เหมืองจี้ อ.เมือง จ.ลำพูน
   - บ้านวัดจามเทวี ต.ต้นธง อ.เมือง จ. ลำพูน
   - รพ.ลำพูน (สาขาเวียงยอง) ต.เวียงยอง อ.เมือง จ.ลำพูน
   - รพ.ลำพูน ต.ต้นธง อ.เมือง จ.ลำพูน
   - รพ.สต.ต้นธง ต.ต้นธง อ.เมือง จ.ลำพูน
   - รพ.สต.ตําบลหนองปลาสะวาย อ.บ้านโฮ่ง จ.ลำพูน
   - รพ.สต.บ้านนากลาง ต.ลี้ อ.ลี้ จ.ลำพูน
   - รพ.สต.บ้านม้า ต.ศรีบัวบาน อ.เมือง จ.ลำพูน
   - รพ.สต.ป่าซางน้อย ต.บ้านแป้น อ.เมือง จ.ลำพูน
   - รพ.สต.ริมปิง ต.ริมปิง อ.เมือง จ.ลำพูน
   - รพ.สต.หนองหล่ม ต.ศรีบัวบาน อ.เมืองลำพูน จ.ลำพูน
   - รพ.สต.เวียงยอง ต.เวียงยอง อ.เมือง จ.ลำพูน
   - รพ.สต.เหมืองจี้ ต.เหมืองจี้ อ.เมือง จ.ลำพูน
   - รร.วัดบ้านก้อง ต. ปากบ่อง อ. ป่าซาง จ.ลำพูน
   - ศพด.บ้านก้อจัดสรร (Outdoor) ต.ลี้ อ.ลี้ จ.ลำพูน
   - ศพด.บ้านก้อจัดสรร (indoor) ต.ลี้ อ.ลี้ จ.ลำพูน
   - ศพด.บ้านปงแม่ลอบ (Indoor) ต.ทาแม่ลอบ อ.แม่ทา จ.ลำพูน
   - ศพด.บ้านปงแม่ลอบ (Outdoor) ต.ทาแม่ลอบ อ.แม่ทา จ.ลำพูน
   - ศพด.วัดสันโป่ง (Indoor) ต.ลี้ อ.ลี้ จ.ลำพูน
   - ศพด.วัดสันโป่ง (Outdoor) ต.ลี้ อ.ลี้ จ.ลำพูน
   - ศูนย์สุขภาพชุมชนลี้ ต.ลี้ อ.ลี้ จ.ลำพูน
   - อบต.ทุ่งหัวช้าง ต.ทุ่งหัวช้าง อ.ทุ่งหัวช้าง จ.ลำพูน
   - อาคาร HPB4 ศูนย์การศึกษามหาวิทยาลัยเชียงใหม่ หริภุญไชย ต.ศรีบัวบาน อ.เมือง จ.ลำพูน
   - เทศบาลตำบลทากาศ ต.ทากาศ อ.แม่ทา จ.ลำพูน
   - เทศบาลตำบลทาปลาดุก ต.ทาปลาดุก อ.แม่ทา จ.ลำพูน
   - เทศบาลตำบลลี้ ต.ลี้ อ.ลี้ จ.ลำพูน
   - เทศบาลตำบลศรีบัวบาน ต.ศรีบัวบาน อ.เมืองลำพูน จ.ลำพูน
   - เทศบาลเมืองลำพูน สถานีดับเพลิง ต.ในเมือง อ.เมืองลำพูน จ.ลำพูน
   - โรงเรียนบ้านฮ่อมต้อ (Outdoor) ต.ลี้ อ.ลี้ จ. ลำพูน
   - โรงเรียนบ้านโฮ่ง  ต.ลี้ อ.ลี้ จ.ลำพูน
------------------------------
📍 เชียงราย (43 stations)
   - ต.ท่าข้าม อ.เวียงแก่น จ.เชียงราย
   - บริษัท ชวี่ เฉวียน ฟูดส์ จำกัด ต.เวียงกาหลง อ.เวียงป่าเป้า จ.เชียงราย
   - บ้านทุ่งยั้ง ต.ผางาม อ.เวียงชัย จ.เชียงราย
   - รพ.ป่าแดด ต.ป่าแดด อ.ป่าแดด จ. เชียงราย
   - รพ.พญาเม็งราย ต.แม่เปา อ.พญาเม็งราย จ.เชียงราย
   - รพ.พาน ต.ม่วงคำ อ.พาน จ.เชียงราย
   - รพ.สต.ดงมหาวัน ต.ดงมหาวัน อ.เวียงเชียงรุ้ง จ.เชียงราย
   - รพ.สต.ทานตะวัน อ.พาน จ.เชียงราย
   - รพ.สต.ธารทอง อ.พาน จ.เชียงราย
   - รพ.สต.บ้านงิ้วเฒ่า ต.ป่าหุ่ง อ.พาน จ.เชียงราย
   - รพ.สต.บ้านจะคือ อ.เมือง จ.เชียงราย
   - รพ.สต.บ้านดงมหาวัน ต.ดงมหาวัน อ.เวียงเชียงรุ้ง จ.เชียงราย
   - รพ.สต.บ้านดงมะตื๋น ต.ผางาม อ.เวียงชัย จ.เชียงราย
   - รพ.สต.บ้านด้าย ต.บ้านด้าย อ.แม่สาย จ.เชียงราย
   - รพ.สต.บ้านทุ่งงิ้ว   อ.เชียงของ  จ.เชียงราย
   - รพ.สต.บ้านป่าบง อ.พาน จ.เชียงราย
   - รพ.สต.บ้านร่องบัวทอง ต.ทุ่งก่อ อ.เวียงเชียงรุ้ง จ.เชียงราย
   - รพ.สต.บ้านโป่งพระบาท  อ.เมือง   จ.เชียงราย
   - รพ.สต.ป่าซาง ต.ป่าซาง อ.เวียงเชียงรุ้ง จ.เชียงราย
   - รพ.สต.สถาน อ.เชียงของ จ.เชียงราย
   - รพ.สต.ห้วยไคร้  อ.แม่สาย จ.เชียงราย
   - รพ.สต.เกาะช้าง ต.เกาะช้าง อ.แม่สาย จ.เชียงราย
   - รพ.สต.แม่เย็น อ.พาน จ.เชียงราย
   - รพ.สมเด็จพระยุพราชเชียงของ ต.เวียง อ.เชียงของ จ.เชียงราย
   - รพ.เชียงรายประชานุเคราะห์ ต.รอบเวียง อ.เมือง จ.เชียงราย
   - รพ.เทิง ต.เวียง อ.เทิง จ.เชียงราย
   - รพ.เวียงป่าเป้า ต.เวียง อ.เวียงป่าเป้า จ.เชียงราย
   - รพ.แม่สรวย ต.แม่พริก อ.แม่สรวย จ.เชียงราย
   - รพ.แม่สาย ต.เวียงพางคำ อ.แม่สาย จ.เชียงราย
   - ศพด.บ้านจะเด้อ (Outdoor) ต.แม่ยาว อ.เมือง จ.เชียงราย
   - ศพด.บ้านจะเด้อ (indoor) ต.แม่ยาว อ.เมือง จ.เชียงราย
   - ศพด.บ้านหัวแม่คำ (Indoor) ต.แม่สลองใน อ.แม่ฟ้าหลวง จ.เชียงราย
   - ศพด.บ้านหัวแม่คำ (Outdoor) ต.แม่สลองใน อ.แม่ฟ้าหลวง จ.เชียงราย
   - ศพด.บ้านเวียงหมอก (Outdoor) ต.ห้วยซ้อ อ.เชียงของ จ.เชียงราย
   - ศพด.บ้านเวียงหมอก (indoor) ต.ห้วยซ้อ อ.เชียงของ จ.เชียงราย
   - ศพด.สันไทรงาม (Outdoor) ต.ดงมหาวัน อ.เวียงเชียงรุ้ง จ.เชียงราย
   - ศพด.สันไทรงาม (indoor) ต.ดงมหาวัน อ.เวียงเชียงรุ้ง จ.เชียงราย
   - ศูนย์พัฒนาเด็กเล็กเทศบาลตำบลแม่สายมิตรภาพ ต.แม่สาย อ.แม่สาย จ.เชียงราย
   - สสจ.เชียงราย ต.ท่าสาย อ.เมือง จ.เชียงราย
   - สสอ.เวียงเชียงรุ้ง ต.ทุ่งก่อ อ.เวียงเชียงรุ้ง จ.เชียงราย
   - ห้องประชุม รพ.สต. ห้วยซ้อ อ.เชียงของ จ.เชียงราย
   - อบต.ศรีถ้อย ต.ศรีถ้อย อ.แม่สรวย จ.เชียงราย (กอ.รมน. เชียงราย)
   - อบต.ศรีเมืองชุม อ.แม่สาย จ.เชียงราย
------------------------------
📍 เชียงใหม่ (129 stations)
   - Bear Hug Cafe‚ ต.ช้างคลาน อ.เมือง จ.เชียงใหม่
   - CR001 ต.บ้านแหวน (Outdoor) อ.หางดง จ.เชียงใหม่
   - CR002 ต.บ้านตลาดใหญ่ (Indoor) อ.ดอยสะเก็ด จ.เชียงใหม่
   - CR002 ต.บ้านตลาดใหญ่ (Outdoor) อ.ดอยสะเก็ด จ.เชียงใหม่
   - CR003 188 ม.2 ต.บ้านแอ่นใหม่ อ.ดอยเต่า จ.เชียงใหม่ (Indoor)
   - CR003 ต.บ้านแอ่น (Indoor) อ.ดอยเต่า จ.เชียงใหม่
   - CR003 ต.บ้านแอ่น (Outdoor) อ.ดอยเต่า จ.เชียงใหม่
   - CR004 (Indoor) ต.แม่ปูคา อ.สันกำแพง จ.เชียงใหม่
   - CR004 (Outdoor) ต.แม่ปูคา อ.สันกำแพง จ.เชียงใหม่
   - CR004 ต.แม่ปูคา อ.สันกำแพง จ.เชียงใหม่
   - CR005 (Indoor)  ต.แม่ปูคา อ.สันกำแพง จ.เชียงใหม่
   - CR005 (Outdoor)  ต.แม่ปูคา อ.สันกำแพง จ.เชียงใหม่
   - CR006 (Indoor) ต.บวกค้าง อ.สันกำแพง จ.เชียงใหม่
   - CR006 (Outdoor)ต.บวกค้าง อ.สันกำแพง จ.เชียงใหม่
   - CR007 (Indoor) ต.ร้องวัวแดง อ.สันกำแพง จ.เชียงใหม่
   - CR007 (Outdoor) ต.ร้องวัวแดง อ.สันกำแพง จ.เชียงใหม่
   - CR008 (Indoor) ต.สันกำแพง อ.สันกำแพง จ.เชียงใหม่
   - CR008 (Outdoor) ต.สันกำแพง อ.สันกำแพง จ.เชียงใหม่
   - CR009 (Indoor) ต.สันกำแพง อ.สันกำแพง จ.เชียงใหม่
   - CR010 (Indoor) ต.สันกำแพง อ.สันกำแพง จ.เชียงใหม่
   - CR011 (Outdoor) ต.ออนใต้ อ.สันกำแพง จ.เชียงใหม่
   - CR011 (indoor) ต.ออนใต้ อ.สันกำแพง จ.เชียงใหม่ (Indoor)
   - CR012 (Outdoor) ต.ห้วยทราย อ.สันกำแพง จ.เชียงใหม่ (Outdoor)
   - CR012 (indoor) ต.ห้วยทราย อ.สันกำแพง จ.เชียงใหม่ (Indoor)
   - CR013  (Outdoor) ต.ห้วยทราย อ.สันกำแพง จ.เชียงใหม่
   - CR013  (indoor) ต.ห้วยทราย อ.สันกำแพง จ.เชียงใหม่ (Indoor)
   - CR014 (Outdoor) ต.ห้วยทราย อ.สันกำแพง จ.เชียงใหม่
   - CR014 (indoor) ต.ห้วยทราย อ.สันกำแพง จ.เชียงใหม่
   - CR015 (Outdoor) ต.สันกำแพง อ.สันกำแพง จ.เชียงใหม่
   - CR015 (indoor) ต.สันกำแพง อ.สันกำแพง จ.เชียงใหม่
   - CR016 (Indoor) ต.สันกลาง อ.สันกำแพง จ.เชียงใหม่
   - CR016 (Outdoor) ต.สันกลาง อ.สันกำแพง จ.เชียงใหม่
   - CR017 (Outdoor)  ต.สันกลาง อ.สันกำแพง จ.เชียงใหม่
   - CR017 (indoor) ต.สันกลาง อ.สันกำแพง จ.เชียงใหม่
   - CR018 (Indoor)  ต.หนองหาร อ.สันทราย จ.เชียงใหม่
   - CR018 (Outdoor)  ต.หนองหาร อ.สันทราย จ.เชียงใหม่
   - CR018 (outdoor)  ต.หนองหาร อ.สันทราย จ.เชียงใหม่
   - CR019 (Outdoor)  ต.สันทรายน้อย อ.สันทราย จ.เชียงใหม่
   - CR019 (indoor) ต.สันทรายน้อย อ.สันทราย จ.เชียงใหม่
   - คณะการสื่อสารมวลชน มช. ต.สุเทพ อ.เมือง จ.เชียงใหม่
   - คณะบริหารธุรกิจ มช. ต.สุเทพ อ.เมือง จ.เชียงใหม่
   - คณะมนุษยศาสตร์ มช. (HB5) ต.สุเทพ อ.เมือง จ.เชียงใหม่
   - คณะสังคมศาสตร์ มช. ต.สุเทพ อ.เมือง จ.เชียงใหม่
   - จุดบริการตำรวจท่องเทียว ต.ศรีภูมิ อ.เมืองเชียงใหม่ จ.เชียงใหม่
   - ชุมชนวัดเกต ต.วัดเกต อ.เมือง จ.เชียงใหม่ จุดที่ 2 (Indoor)
   - ชุมชนวัดเกต ต.วัดเกต อ.เมือง จ.เชียงใหม่ จุดที่ 6 (Indoor) สำรอง
   - ชุมชนสวนดอก ต.สุเทพ อ.เมือง จ.เชียงใหม่
   - ตึกดินและปุ๋ย คณะผลิตกรรมการเกษตร ม.แม่โจ้ ต.หนองหาร อ.สันทราย จ.เชียงใหม่
   - ทต.เมืองนะ ต.เมืองนะ อ.เชียงดาว จ.เชียงใหม่
   - ธรรมปกรณ์ อาคารชาย 2 (Indoor) ต.พระสิงห์ อ.เมือง จ.เชียงใหม่
   - ธรรมปกรณ์ อาคารผู้ป่วย (Indoor) ต.พระสิงห์ อ.เมือง จ.เชียงใหม่
   - ธรรมปกรณ์ อาคารหญิง 3 (Indoor) ต.พระสิงห์ อ.เมือง จ.เชียงใหม่
   - บก.ฉก.ม.4 ค่ายพิชิตปรีชากร ต.ปิงโค้ง อ.เชียงดาว จ.เชียงใหม่ (กอ.รมน.ภาค 3 สย.2)
   - บริษัท ฮาร์ท ทู เอิร์ธ จำกัด ต.บ้านแหวน อ.หางดง จ.เชียงใหม่
   - บริษัท เชอวาล เทคโนโลยี่ จำกัด ต.แช่ช้าง อ.สันกำแพง จ.เชียงใหม่
   - บริษัท ไบโอ ครีโนเวชั่น จำกัด ต.สันกลาง อ.สันป่าตอง จ.เชียงใหม่
   - บ้านกาญจน์กนก 2 เฟส 3   ต.สันปูเลย อ.ดอยสะเก็ด จ.เชียงใหม่
   - บ้านดอยสันเกี๋ยง ต.ช่างเคิ่ง อ.แม่แจ่ม จ.เชียงใหม่
   - บ้านผาแดง ต.แม่ปั๋ง อ.พร้าว จ.เชียงใหม่
   - บ้านหนองครก ต.สันทราย อ.พร้าว จ.เชียงใหม่
   - บ้านหัวโท ม. 6 ต.ปิงโค้ง อ.เชียงดาว จ.เชียงใหม่
   - บ้านห้วยบงใต้ ต.เขื่อนผาก อ.พร้าว จ.เชียงใหม่
   - บ้านแม่ปั๋ง ต.แม่ปั๋ง อ.พร้าว จ.เชียงใหม่
   - บ้านแสนสราญ ต.หนองควาย อ.หางดง จ.เชียงใหม่
   - ประตูหน้า มช. ต.สุเทพ อ.เมือง จ.เชียงใหม่
   - มช. แคมปัสแม่เหียะ ต.สุเทพ อ.เมือง จ.เชียงใหม่
   - รพ.ดอยหล่อ ต.ดอยหล่อ อ.ดอยหล่อ จ.เชียงใหม่
   - รพ.ฝาง ต.เวียง อ.ฝาง จ.เชียงใหม่
   - รพ.พร้าว ต.เวียง อ.พร้าว จ.เชียงใหม่
   - รพ.สต.บ้านทุ่งข้าวพวง ต.ทุ่งข้าวพวง อ.เชียงดาว จ.เชียงใหม่
   - รพ.สต.บ้านปงตำ ต.ปงตำ อ.ไชยปราการ จ.เชียงใหม่
   - รพ.สต.บ้านปางมะเยา ต.ปิงโค้ง อ.เชียงดาว จ.เชียงใหม่
   - รพ.สต.บ้านปางเฟือง ต.ปิงโค้ง อ.เชียงดาวจ.เชียงใหม่
   - รพ.สต.บ้านอรุโณทัย อ.เชียงดาว จ.เชียงใหม่
   - รพ.สต.บ้านเมืองงาย ต.เมืองงาย อ.เชียงดาว จ.เชียงใหม่
   - รพ.สต.แม่แดดน้อย ต.แม่แดด อ.กัลยาณิวัฒนา จ.เชียงใหม่
   - รพ.สันกำแพง ต.บวกค้าง อ.สันกำแพง จ.เชียงใหม่
   - รพ.สันป่าตอง ต.ยุหว่า อ.สันป่าตอง จ.เชียงใหม่
   - รพ.สันป่าตอง(2) ต.ยุหว่า อ.สันป่าตอง จ.เชียงใหม่
   - รพ.สารภี ต.สารภี อ.สารภี จ.เชียงใหม่
   - รพ.ส่งเสริมสุขภาพ เขต1 ต.ช้างคลาน อ.เมืองเชียงใหม่ จ.เชียงใหม่
   - รพ.หางดง ต.หางดง อ.หางดง จ.เชียงใหม่
   - รพ.ฮอด ต.หางดง อ.ฮอด จ.เชียงใหม่
   - รพ.เชียงดาว ต.เชียงดาว อ.เชียงดาว จ.เชียงใหม่
   - รพ.เทพรัตนเวชชานุกูล ต.ช่างเคิ่ง อ.แม่แจ่ม จ.เชียงใหม่
   - รพ.แม่ออน ต.บ้านสหกรณ์ อ.แม่ออน จ.เชียงใหม่
   - รพ.แม่อาย ต.แม่อาย อ.แม่อาย จ.เชียงใหม่
   - รพ.แม่แตง ต.สันมหาพน อ.แม่แตง จ.เชียงใหม่
   - รพ.ไชยปราการ ต.ศรีดงเย็น อ.ไชยปราการ จ.เชียงใหม่
   - รร.บ้านคุณแม่ ต.หนองควาย อ.หางดง จ.เชียงใหม่
   - รร.บ้านปางเฟือง ต.ปิงโค้ง อ.เชียงดาว จ.เชียงใหม่
   - รร.บ้านออน ต.ปิงโค้ง อ.เชียงดาว จ.เชียงใหม่
   - รร.วัดศรีโพธาราม ต.สารภี อ.สารภี จ.เชียงใหม่
   - รร.อนุบาลมยุรี ต.แม่เหียะ อ.เมือง จ.เชียงใหม่
   - ศพด.บวกครกน้อย (Indoor) ต.หนองป่าครั่ง อ.เมือง จ.เชียงใหม่
   - ศพด.บวกครกน้อย (Outdoor) ต.หนองป่าครั่ง อ.เมือง จ.เชียงใหม่
   - ศพด.บ้านเมืองนะ (Indoor) ต.เมืองนะ อ.เชียงดาว จ.เชียงใหม่
   - ศพด.บ้านเมืองนะ (Outdoor) ต.เมืองนะ อ.เชียงดาว จ.เชียงใหม่
   - ศพด.บ้านแม่หอพระ (Indoor) ต.แม่หอพระ อ.แม่แตง จ.เชียงใหม่
   - ศพด.บ้านแม่หอพระ (Outdoor) ต.แม่หอพระ อ.แม่แตง จ.เชียงใหม่
   - ศพด.เทศบาลตำบลสันผักหวาน (Indoor) ต.สันผักหวาน อ.หางดง จ.เชียงใหม่
   - ศพด.เทศบาลตำบลสันผักหวาน (Outdoor) ต.สันผักหวาน อ.หางดง จ.เชียงใหม่
   - ศูนย์พัฒนาเด็กเล็กตำบลสันโป่ง (Outdoor) ต.สันโป่ง อ.แม่ริม จ.เชียงใหม่
   - ศูนย์พัฒนาเด็กเล็กตำบลสันโป่ง (indoor) ต.สันโป่ง อ.แม่ริม จ.เชียงใหม่
   - ศูนย์ส่งเสริมพฤฒพลังผู้สูงอายุ มช. ต.ช้างคลาน อ.เมือง จ.เชียงใหม่ (outdoor)
   - สถานบริการสาธารณสุขชุมชนบ้านเมืองนะ ต.เมืองนะ อ.เชียงดาว จ.เชียงใหม่
   - สถานีวิจัยสัตว์ป่าดอยเชียงดาว ต.เชียงดาว อ.เชียงดาว จ.เชียงใหม่
   - สถานเลี้ยงเด็กกลางวันสำหรับครอบครัวนมแม่ (Indoor) ต.ช้างคลาน อ.เมือง จ.เชียงใหม่
   - สถานเลี้ยงเด็กกลางวันสำหรับครอบครัวนมแม่ (Outdoor) ต.ช้างคลาน อ.เมือง จ.เชียงใหม่
   - สถาบันนโยบายสาธารณะ มช. ต.สุเทพ อ.เมือง จ.เชียงใหม่
   - สถาบันวิจัยพหุศาสตร์ มช. ต.สุเทพ อ.เมือง จ.เชียงใหม่
   - สระว่ายน้ำ สนามกีฬา 700 ปี ต.ดอนแก้ว อ.แม่ริม จ.เชียงใหม่
   - สสอ.จอมทอง ต.ดอยแก้ว อ.จอมทอง จ.เชียงใหม่
   - สสอ.ดอยเต่า ต.ดอยเต่า อ.ดอยเต่า จ.เชียงใหม่
   - สสอ.พร้าว ต.เวียง อ.พร้าว จ.เชียงใหม่
   - สสอ.ฮอด ต.หางดง อ.ฮอด จ.เชียงใหม่
   - สสอ.เชียงดาว ต.เชียงดาว อ.เชียงดาว จ. เชียงใหม่
   - หน่วยพิทักษ์ป่าสบห้วยผาตั้ง-นาเลา ต.เชียงดาว อ.เชียงดาว จ.เชียงใหม่
   - ห้องกิจกรรม E3 ศูนย์ส่งเสริมพฤฒพลังผู้สูงอายุ มช. ต.ช้างคลาน อ.เมือง จ.เชียงใหม่ (indoor)
   - ห้องปฏิบัติการจุลชีววิทยาคลินิก 1 อาคาร 2 คณะเทคนิคการแพทย์ มช. ต.สุเทพ อ.เมือง จ.เชียงใหม่ (indoor)
   - ห้องฟิตเนส ศูนย์ส่งเสริมพฤฒพลังผู้สูงอายุ มช. ต.ช้างคลาน อ.เมือง จ.เชียงใหม่ (indoor)
   - ห้างหุ้นส่วนจำกัด ต.ดริ๊งค์ ต.สันกลาง อ.สันกำแพง จ.เชียงใหม่
   - อาคาร 40 ปี คณะวิทยาศาสตร์ มช. ต.สุเทพ อ.เมือง จ.เชียงใหม่
   - อาคาร1 บ้านธรรมปกรณ์ (Indoor) ต.พระสิงห์ อ.เมือง จ.เชียงใหม่
   - โรงพยาบาลอมก๋อย ต.อมก๋อย อ.อมก๋อย จ.เชียงใหม่
   - โรงพยาบาลแม่ตื่น ต.แม่ตื่น อ.อมก๋อย จ.เชียงใหม่
   - โรงพยาบาลแม่วาง ต.บ้านกาด อ.แม่วาง จ.เชียงใหม่
   - โรงอาหารคณะวิศวกรรมศาสตร์ มช. ต.สุเทพ อ.เมือง จ.เชียงใหม่
   - ไนท์บาร์ซาร์ ต.ช้างม่อย อ.เมือง จ. เชียงใหม่
------------------------------
📍 แพร่ (13 stations)
   - รพ.ลอง ต.ห้วยอ้อ อ.ลอง จ.แพร่
   - รพ.วังชิ้น ต.วังชิ้น อ.วังชิ้น จ.แพร่
   - รพ.สต.ทุ่งแค้ว อ.หนองม่วงไข่ จ.แพร่
   - รพ.สมเด็จพระยุพราชเด่นชัย ต.เด่นชัย อ.เด่นชัย จ.แพร่
   - รพ.สอง ต.บ้านหนุน อ.สอง จ.แพร่
   - รพ.สูงเม่น ต.พระหลวง อ.สูงเม่น จ.แพร่
   - รพ.แพร่ ต.ในเวียง อ.เมือง จ.แพร่
   - ศูนย์พัฒนาเด็กเล็กบ้านแม่ป้าก (Indoor) อบต.แม่ป้าก ต.แม่ป้าก อ.วังชิ้น จ.แพร่
   - ศูนย์พัฒนาเด็กเล็กบ้านแม่ป้าก (Outdoor) อบต.แม่ป้าก ต.แม่ป้าก อ.วังชิ้น จ.แพร่
   - สสจ.แพร่ ต.ในเวียง อ.เมือง จ.แพร่
   - สสอ.หนองม่วงไข่ ต.หนองม่วงไข่ อ.หนองม่วงไข่ จ.แพร่
   - องค์การบริหารส่วนจังหวัดแพร่ ต.ในเวียง อ.เมืองแพร่ จ.แพร่
   - โรงพยาบาลร้องกวาง ต.ร้องเข็ม อ.ร้องกวาง จ.แพร่
------------------------------
📍 แม่ฮ่องสอน (28 stations)
   - ต.เวียงเหนือ อ.ปาย จ.แม่ฮ่องสอน
   - รพ.ขุนยวม ต.ขุนยวม อ.ขุนยวม จ.แม่ฮ่องสอน
   - รพ.ปางมะผ้า ต.สบป่อง อ.ปางมะผ้า จ.แม่ฮ่องสอน
   - รพ.ปาย ต.เวียงใต้ อ.ปาย จ.แม่ฮ่องสอน
   - รพ.สต.ต่อแพ ต.แม่เงา อ.ขุนยวม จ.แม่ฮ่องสอน
   - รพ.สต.ท่าหินส้ม อ.ขุนยวม จ.แม่ฮ่องสอน
   - รพ.สต.บ้านสาม อ.แม่ลาน้อย จ.แม่ฮ่องสอน
   - รพ.สต.ห้วยสิงห์ อ.แม่สะเรียง จ.แม่ฮ่องสอน
   - รพ.สต.แม่ลาหลวง ต.แม่ลาหลวง อ.แม่ลาน้อย จ.แม่ฮ่องสอน
   - รพ.สต.แม่ฮี้ ต.แม่ฮี้ อ.ปาย จ.แม่ฮ่องสอน
   - รพ.สบเมย ต.แม่คะตวน อ.สบเมย จ.แม่ฮ่องสอน
   - รพ.แม่ลาน้อย ต.แม่ลาน้อย อ.แม่ลาน้อย จ.แม่ฮ่องสอน
   - รร.บ้านน้ำฮู ต.เวียงใต้ อ.ปาย จ.แม่ฮ่องสอน
   - ศพด.บ้านนาปู่ป้อม (indoor) ต.นาปู่ป้อม อ.ปางมะผ้า จ.แม่ฮ่องสอน
   - ศพด.บ้านนาปู่ป้อม (outdoor) ต.นาปู่ป้อม อ.ปางมะผ้า จ.แม่ฮ่องสอน
   - ศพด.บ้านม่วงสร้อย (Indoor) ต.แม่นาเติง อ.ปาย จ.แม่ฮ่องสอน
   - ศพด.บ้านม่วงสร้อย (Outdoor) ต.แม่นาเติง อ.ปาย จ.แม่ฮ่องสอน
   - ศพด.ประจำตำบลแม่สะเรียง (indoor) ต.แม่สะเรียง อ.แม่สะเรียง จ.แม่ฮ่องสอน
   - ศพด.ประจำตำบลแม่สะเรียง (outdoor) ต.แม่สะเรียง อ.แม่สะเรียง จ.แม่ฮ่องสอน
   - ศพด.แม่ฮี้ (Indoor) ต.แม่ฮี้ อ.ปาย จ.แม่ฮ่องสอน
   - ศพด.แม่ฮี้ (Outdoor) ต.แม่ฮี้ อ.ปาย จ.แม่ฮ่องสอน
   - สสจ.แม่ฮ่องสอน (indoor) ต.จองคำ อ.เมือง จ.แม่ฮ่องสอน
   - สสอ.ขุนยวม ต.ขุนยวม อ.ขุนยวม จ.แม่ฮ่องสอน
   - สำนักงานสาธารณสุขจังหวัดแม่ฮ่องสอน ต.จองคำ อ.เมือง จ.แม่ฮ่องสอน
   - ห้องประชุมสาละวิน อบต.แม่สามแลบ ต.แม่สามแลบ อ.สบเมย จ.แม่ฮ่องสอน
   - อบต.เวียงใต้ อ.ปาย จ.แม่ฮ่องสอน
   - อาคารสาละวินบ้านแม่สามแลบ ต.แม่สามแลบ อ.สบเมย จ.แม่ฮ่องสอน
   - โรงพยาบาลธัญญารักษ์แม่ฮ่องสอน ต.ปางหมู อ.เมือง จ.แม่ฮ่องสอน
------------------------------