In [1]:
import pandas as pd
import numpy as np

In [2]:
real = pd.read_csv('/Users/tamsopanat/Desktop/MedCMU - FamMed/Dustboy/result/pm25.csv', usecols=[0,3,4,5,6,7,8,9,10]).dropna()
real

,datetime,province,amphoe,tambon,local_name,pm25,pm10,temp,humid
18072,2026-01-01 00:00:00,ลำปาง,แม่เมาะ,จางเหนือ,ศพด.อบต.จางเหนือ (Outdoor) ต.จางเหนือ อ.แม่เมา...,33.00,37.22,23.23,57.53
18073,2026-01-01 01:00:00,ลำปาง,แม่เมาะ,จางเหนือ,ศพด.อบต.จางเหนือ (Outdoor) ต.จางเหนือ อ.แม่เมา...,32.33,36.89,22.70,57.93
18074,2026-01-01 02:00:00,ลำปาง,แม่เมาะ,จางเหนือ,ศพด.อบต.จางเหนือ (Outdoor) ต.จางเหนือ อ.แม่เมา...,29.56,32.44,22.18,58.46
18075,2026-01-01 03:00:00,ลำปาง,แม่เมาะ,จางเหนือ,ศพด.อบต.จางเหนือ (Outdoor) ต.จางเหนือ อ.แม่เมา...,28.44,30.22,21.70,58.95
18076,2026-01-01 04:00:00,ลำปาง,แม่เมาะ,จางเหนือ,ศพด.อบต.จางเหนือ (Outdoor) ต.จางเหนือ อ.แม่เมา...,27.78,29.22,21.25,59.60
...,...,...,...,...,...,...,...,...,...
2057519,2026-07-16 19:00:00,ลำปาง,แม่เมาะ,จางเหนือ,วัดปงแท่น หมู่บ้านปงแท่น ต.จางเหนือ อ.แม่เมาะ ...,7.11,12.56,24.53,91.93
2057520,2026-07-16 20:00:00,ลำปาง,แม่เมาะ,จางเหนือ,วัดปงแท่น หมู่บ้านปงแท่น ต.จางเหนือ อ.แม่เมาะ ...,9.89,15.89,24.22,92.90
2057521,2026-07-16 21:00:00,ลำปาง,แม่เมาะ,จางเหนือ,วัดปงแท่น หมู่บ้านปงแท่น ต.จางเหนือ อ.แม่เมาะ ...,12.78,17.00,24.21,93.93
2057522,2026-07-16 22:00:00,ลำปาง,แม่เมาะ,จางเหนือ,วัดปงแท่น หมู่บ้านปงแท่น ต.จางเหนือ อ.แม่เมาะ ...,12.11,17.33,24.33,93.87
2057523,2026-07-16 23:00:00,ลำปาง,แม่เมาะ,จางเหนือ,วัดปงแท่น หมู่บ้านปงแท่น ต.จางเหนือ อ.แม่เมาะ ...,12.00,17.00,24.37,93.60

In [3]:
real['local_name'] = real['local_name'].str.split(' ต.').str[0]
real

,datetime,province,amphoe,tambon,local_name,pm25,pm10,temp,humid
18072,2026-01-01 00:00:00,ลำปาง,แม่เมาะ,จางเหนือ,ศพด.อบต.จางเหนือ (Outdoor),33.00,37.22,23.23,57.53
18073,2026-01-01 01:00:00,ลำปาง,แม่เมาะ,จางเหนือ,ศพด.อบต.จางเหนือ (Outdoor),32.33,36.89,22.70,57.93
18074,2026-01-01 02:00:00,ลำปาง,แม่เมาะ,จางเหนือ,ศพด.อบต.จางเหนือ (Outdoor),29.56,32.44,22.18,58.46
18075,2026-01-01 03:00:00,ลำปาง,แม่เมาะ,จางเหนือ,ศพด.อบต.จางเหนือ (Outdoor),28.44,30.22,21.70,58.95
18076,2026-01-01 04:00:00,ลำปาง,แม่เมาะ,จางเหนือ,ศพด.อบต.จางเหนือ (Outdoor),27.78,29.22,21.25,59.60
...,...,...,...,...,...,...,...,...,...
2057519,2026-07-16 19:00:00,ลำปาง,แม่เมาะ,จางเหนือ,วัดปงแท่น หมู่บ้านปงแท่น,7.11,12.56,24.53,91.93
2057520,2026-07-16 20:00:00,ลำปาง,แม่เมาะ,จางเหนือ,วัดปงแท่น หมู่บ้านปงแท่น,9.89,15.89,24.22,92.90
2057521,2026-07-16 21:00:00,ลำปาง,แม่เมาะ,จางเหนือ,วัดปงแท่น หมู่บ้านปงแท่น,12.78,17.00,24.21,93.93
2057522,2026-07-16 22:00:00,ลำปาง,แม่เมาะ,จางเหนือ,วัดปงแท่น หมู่บ้านปงแท่น,12.11,17.33,24.33,93.87
2057523,2026-07-16 23:00:00,ลำปาง,แม่เมาะ,จางเหนือ,วัดปงแท่น หมู่บ้านปงแท่น,12.00,17.00,24.37,93.60

In [4]:
real = real[real['province'].isin(['เชียงราย', 'เชียงใหม่', 'แม่ฮ่องสอน', 'ลำปาง', 'ลำพูน', 'น่าน', 'แพร่', 'พะเยา'])]
real = real[real['datetime'] >= '2026-04-01 00:00:00']
real = real[['datetime', 'province', 'amphoe', 'tambon', 'local_name', 'pm25', 'temp']]
real.columns = ['date','province','amphoe','tambon','local_name','pm25_avg','temperature_avg']
real.to_csv('./environmental.csv', index= False)
real

,date,province,amphoe,tambon,local_name,pm25_avg,temperature_avg
966619,2026-04-01 00:00:00,ลำปาง,แม่เมาะ,จางเหนือ,ศพด.อบต.จางเหนือ (Outdoor),138.67,31.82
966620,2026-04-01 01:00:00,ลำปาง,แม่เมาะ,จางเหนือ,ศพด.อบต.จางเหนือ (Outdoor),149.78,31.17
966621,2026-04-01 02:00:00,ลำปาง,แม่เมาะ,จางเหนือ,ศพด.อบต.จางเหนือ (Outdoor),170.00,30.53
966622,2026-04-01 03:00:00,ลำปาง,แม่เมาะ,จางเหนือ,ศพด.อบต.จางเหนือ (Outdoor),202.50,30.14
966623,2026-04-01 04:00:00,ลำปาง,แม่เมาะ,จางเหนือ,ศพด.อบต.จางเหนือ (Outdoor),301.91,29.37
...,...,...,...,...,...,...,...
2057519,2026-07-16 19:00:00,ลำปาง,แม่เมาะ,จางเหนือ,วัดปงแท่น หมู่บ้านปงแท่น,7.11,24.53
2057520,2026-07-16 20:00:00,ลำปาง,แม่เมาะ,จางเหนือ,วัดปงแท่น หมู่บ้านปงแท่น,9.89,24.22
2057521,2026-07-16 21:00:00,ลำปาง,แม่เมาะ,จางเหนือ,วัดปงแท่น หมู่บ้านปงแท่น,12.78,24.21
2057522,2026-07-16 22:00:00,ลำปาง,แม่เมาะ,จางเหนือ,วัดปงแท่น หมู่บ้านปงแท่น,12.11,24.33
2057523,2026-07-16 23:00:00,ลำปาง,แม่เมาะ,จางเหนือ,วัดปงแท่น หมู่บ้านปงแท่น,12.00,24.37

In [5]:
import csv
import random
import math
from datetime import datetime, timedelta

locations = {}
for province, amphoe, tambon in real[['province', 'amphoe', 'tambon']].drop_duplicates().itertuples(index=False):
    locations.setdefault(province, {}).setdefault(amphoe, []).append(tambon)

start_date = datetime(2026, 4, 1, 0, 0, 0)
end_date = datetime(2026, 6, 30, 23, 0, 0)
num_days = (end_date - start_date).days
num_hours = num_days * 24


pat_filename = "patients.csv"
pat_headers = [
    "patient_id", "name_masked", "sex", "age", "province", "amphoe", "tambon", "last_contact_date",
    "age_over_65", "age_under_5", "pregnant", "bedridden_immobile", "outdoor_worker", 
    "copd", "asthma", "cardiovascular_disease", "diabetes", "ckd", "hypertension", "lung_cancer", "post_covid"
]

thai_first_names = ["Somchai", "Mali", "Anong", "Kittipong", "Siriporn", "Nattapong", "Wipawan", "Surasak", "Pornthip", "Arunee"]
thai_last_initials = ["P.", "S.", "W.", "K.", "T.", "N.", "J.", "M."]

with open(pat_filename, mode="w", newline="", encoding="utf-8") as f:
    writer = csv.writer(f)
    writer.writerow(pat_headers)
    
    # Generate 1500 mock patients to fill the expanded province/amphoe list
    for i in range(1, 2000):
        pid = f"PID-{random.randint(1000, 9999)}"
        name = f"{random.choice(thai_first_names)} {random.choice(thai_last_initials)}"
        sex = random.choice(["M", "F"])
        age = random.randint(2, 90)
        
        # Select random location from hierarchy
        prov = random.choice(list(locations.keys()))
        amphoe = random.choice(list(locations[prov].keys()))
        tambon = random.choice(locations[prov][amphoe])
        
        # Generate a recent contact date
        contact_days_ago = random.randint(1, 60)
        contact_date = (start_date + timedelta(days=num_days) - timedelta(days=contact_days_ago)).strftime("%Y-%m-%d")
        
        # Demographics booleans
        age_over_65 = age > 65
        age_under_5 = age < 5
        pregnant = sex == "F" and 18 <= age <= 40 and random.random() < 0.05
        bedridden_immobile = age_over_65 and random.random() < 0.2
        outdoor_worker = 18 <= age <= 60 and random.random() < 0.3
        
        # Health conditions booleans (weighted by age roughly)
        age_factor = age / 100
        copd = random.random() < (0.1 + age_factor * 0.3)
        asthma = random.random() < 0.15
        cvd = random.random() < (0.05 + age_factor * 0.4)
        diabetes = random.random() < (0.05 + age_factor * 0.3)
        ckd = random.random() < (0.02 + age_factor * 0.2)
        hypertension = random.random() < (0.1 + age_factor * 0.5)
        lung_cancer = random.random() < (0.01 + age_factor * 0.1)
        post_covid = random.random() < 0.2
        
        writer.writerow([
            pid, name, sex, age, prov, amphoe, tambon, contact_date,
            age_over_65, age_under_5, pregnant, bedridden_immobile, outdoor_worker,
            copd, asthma, cvd, diabetes, ckd, hypertension, lung_cancer, post_covid
        ])

print(f"✅ Generated {pat_filename} successfully.")

✅ Generated patients.csv successfully.